definitions:
  common.Response:
    properties:
      result: {}
      status:
        type: boolean
      status_code:
        type: integer
    type: object
info:
  contact: {}
paths:
  /intialize/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok" "返回用户信息
          schema:
            type: string
        "400":
          description: err_code：10002 参数错误； err_code：10003 校验错误
          schema:
            type: string
        "401":
          description: err_code：10001 登录失败
          schema:
            type: string
        "500":
          description: err_code：20001 服务错误；err_code：20002 接口错误；err_code：20003 无数据错误；err_code：20004
            数据库异常；err_code：20005 缓存异常
          schema:
            type: string
      summary: Server Greeting
      tags:
      - Initialize
  /intialize/ping:
    get:
      consumes:
      - application/json
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: Test Api Server
      tags:
      - Initialize
swagger: "2.0"
